server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

#logging:
#  level:
#    com.bjpowernode.feign.UserOrderFeign: debug  # 我需要答应这个接口下面的日志