server:
  port: 8761
spring:
  application:
    name: eureka-service
eureka:
  server:
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka