server:
    port: 8082
spring:
    application:
        name: user-service
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            probability: 1
            rate: 10
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
feign:
    hystrix:
        enabled: true
