server:
  port:8082
spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
ribbon:
  eager-load:
    clients: true
  eureka:
    enabled: true
  http:
    client:
      enabled: false
  okhttp:
    enabled: false
