server:
  port: 8763
spring:
  application:
    name: eureka-server
eureka:
  server:
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.85
  instance:
    hostname: peer3
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5


